#!/bin/bash

echo "> Install/Update go packages"
go get -u github.com/dougm/goflymake
go get -u github.com/rogpeppe/godef
go get -u github.com/nsf/gocode
go get -u github.com/kisielk/errcheck
go get -u golang.org/x/tools/cmd/oracle
go get -u golang.org/x/tools/cmd/gorename
go get -u golang.org/x/tools/cmd/benchcmp
go get -u golang.org/x/tools/cmd/callgraph
go get -u golang.org/x/tools/cmd/goimports
go get -u golang.org/x/tools/cmd/vet
go get -u github.com/jstemmer/gotags
# go get -u github.com/motemen/gore
go get -u github.com/k0kubun/pp
go get -u github.com/smartystreets/goconvey
# go get -u github.com/tools/godep
go get -u github.com/Masterminds/glide
go get -u github.com/constabulary/gb/...
go get -u github.com/alecthomas/gometalinter
gometalinter --install --update
