#!/bin/bash

echo "> Install/Update go packages"
go get -u github.com/dougm/goflymake
go get -u code.google.com/p/rog-go/exp/cmd/godef
go get -u github.com/nsf/gocode
go get -u github.com/kisielk/errcheck
go get -u code.google.com/p/go.tools/cmd/oracle
go get -u code.google.com/p/go.tools/cmd/gorename
go get -u code.google.com/p/go.tools/cmd/benchcmp
go get -u code.google.com/p/go.tools/cmd/callgraph
go get -u golang.org/x/tools/cmd/goimports
go get -u golang.org/x/tools/cmd/vet
go get -u github.com/jstemmer/gotags
go get -u github.com/motemen/gore
go get -u github.com/k0kubun/pp
go get -u github.com/smartystreets/goconvey
